development:
  bucket: barkhood-development
  access_key_id: AKIAI6YIHQWXWIMT2GBQ
  secret_access_key: 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

test:
  bucket: barkhood-test
  access_key_id: AKIAI6YIHQWXWIMT2GBQ
  secret_access_key: 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

production:
  bucket: barkhood-production
  access_key_id: AKIAI6YIHQWXWIMT2GBQ
  secret_access_key: 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
