# Gmail SMTP credentials for dev/test
gmail_username: anton@prilet.com
gmail_password: Makxis12

# restful_authentication
rest_auth_site_key:

# production database
prod_db_username: app_user
prod_db_password: RX78Gzi8

# GitHub
github_deploy_password: ssMakxis!23h

# Backup gem encrypt password
backup_encrypt_password: baMakxis!23ckup